### ISSUE TITLE
ignore I2C reply-failure for simulator

### ISSUE THREAD

**Issue by ladyada** [adafruit/pxt-seesaw#12]
![image](https://user-images.githubusercontent.com/1214161/41306355-e4d84e3a-6e43-11e8-9aac-d8784b10702a.png)

> Right….. currently the seesaw library sends an i2c message and expects a precise message back. If not, it blows up with a PANIC code. Our in-browser simulator does support emulating seesaw so this happens.
>  
> Could we tweak the pxt-seesaw library to just keep going happily and ignore all subsequent calls?

**Comment by ladyada** [comment]
@pelikhan hey i have pxt up and running but i need Advice on how to fix this properly since its my first change. i think i know what to do, but if you can be around to help i want to know a little more about the error management in pxt :)

**Comment by pelikhan** [comment]
IMO, the seesaw should keep trying to connect to the crickit until it succeeds -- and ignore the error otherwise. Typically, kid friendly runtime are **never** crash

**Comment by ladyada** [comment]
@deanm1278 is this fixed?
