### ISSUE TITLE
Add repo to travis

### ISSUE THREAD

**Issue by pelikhan** [adafruit/pxt-seesaw#2]
It's already setup, just need to add it to get builds.

**Comment by ladyada** [comment]
done

**Comment by ladyada** [comment]
didnt pass fyi!
https://travis-ci.org/adafruit/pxt-seesaw/builds/372829306

**Comment by pelikhan** [comment]
I see the issue. I’ll get it green.

_____________________________

**Comment by pelikhan** [comment]
All green now :)
