### ISSUE TITLE
Move crickit.ts to pxt-crickit

### ISSUE THREAD

**Issue by pelikhan** [adafruit/pxt-seesaw#8]
No reason to keep this file around here:

https://github.com/adafruit/pxt-seesaw/blob/master/crickit.ts

**Comment by deanm1278** [comment]
ok see here: https://github.com/adafruit/pxt-seesaw/commit/004d4bd5d648e57810ae0aa76808e0304f1b7124

and here: https://github.com/adafruit/pxt-crickit/pull/5
